Traceback (most recent call last):
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/55093290/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/55093290/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sympy as sp

def P(z):
    return 1 + 1/3 * z + 1/16 * z ** 2

def Q(z):
    return 1 - 2/3 * z + 1/6 * z ** 2

# Check roots of Q(z)
sp.pprint(sp.solve(Q(z)))

# Check E(y) >= 0
y = sp.symbols('y')
sp.pprint(sp.simplify(Q(1j * y) * Q(-1j * y) - P(1j * y) * P(-1j * y)))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 10[0m
[1;32m      7[0m     [38;5;28;01mreturn[39;00m [38;5;241m1[39m [38;5;241m-[39m [38;5;241m2[39m[38;5;241m/[39m[38;5;241m3[39m [38;5;241m*[39m z [38;5;241m+[39m [38;5;241m1[39m[38;5;241m/[39m[38;5;241m6[39m [38;5;241m*[39m z [38;5;241m*[39m[38;5;241m*[39m [38;5;241m2[39m
[1;32m      9[0m [38;5;66;03m# Check roots of Q(z)[39;00m
[0;32m---> 10[0m sp[38;5;241m.[39mpprint(sp[38;5;241m.[39msolve(Q(z)))
[1;32m     12[0m [38;5;66;03m# Check E(y) >= 0[39;00m
[1;32m     13[0m y [38;5;241m=[39m sp[38;5;241m.[39msymbols([38;5;124m'[39m[38;5;124my[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'z' is not defined
NameError: name 'z' is not defined

